import wtf from 'wtf_wikipedia';
import fs from 'fs';

// ="`"&B1&"`," - excel

const arr = [
  `Albert Einstein`,
  `Switzerland`,
  `Tina Turner`,
  `Yul Brynner`,
  `Empress Elisabeth of Austria`,
  `The Wolf of Wall Street (2013 film)`,
  `French language`,
  `List of countries by foreign-exchange reserves`,
  `Roger Federer`,
  `German language`,
  `Carl Jung`,
  `Napoleon III`,
  `House of Habsburg`,
  `Alisha Lehmann`,
  `Absinthe`,
  `Ursula Andress`,
  `Manuel Akanji`,
  `Nestlй`,
  `Dada`,
  `Richard Wagner`,
  `Ferdinand Marcos`,
  `Yann Sommer`,
  `Lawrence Stroll`,
  `Geneva`,
  `Geneva Conventions`,
  `Bernese Mountain Dog`,
  `Italian language`,
  `Zьrich`,
  `Romance languages`,
  `Jean-Jacques Rousseau`,
  `Granit Xhaka`,
  `James Joyce`,
  `Credit Suisse`,
  `Klaus Schwab`,
  `Habsburg monarchy`,
  `World Economic Forum`,
  `YMCA`,
  `Leonhard Euler`,
  `A Cure for Wellness`,
  `Roman Polanski sexual abuse case`,
  `Rolex`,
  `Romain Grosjean`,
  `Ivan Rakitic`,
  `Roberto Di Matteo`,
  `Jorge Luis Borges`,
  `UBS`,
  `SIG Sauer P226`,
  `Romansh language`,
  `Rhine`,
  `Kat Graham`,
  `St. Bernard (dog)`,
  `Large Hadron Collider`,
  `Alps`,
  `CERN`,
  `John Calvin`,
  `Enes Kanter Freedom`,
  `Basel`,
  `Stan Wawrinka`,
  `Languages of Switzerland`,
  `Jean-Luc Godard`,
  `Claudio Castagnoli`,
  `SIG Sauer`,
  `Bern`,
  `List of countries and territories where French is an official language`,
  `Toblerone`,
  `Matterhorn`,
  `Akira Schmid`,
  `2022–2023 mpox outbreak`,
  `FC Basel`,
  `Hermann Hesse`,
  `2023 IIHF World U18 Championships`,
  `Bata Corporation`,
  `Paul Klee`,
  `Muesli`,
  `Swiss franc`,
  `Rudolf Steiner`,
  `Albert Hofmann`,
  `Le Corbusier`,
  `Raclette`,
  `Philip Morris International`,
  `ABB`,
  `Patek Philippe`,
  `Pilatus PC-12`,
  `Xherdan Shaqiri`,
  `Richemont`,
  `Arpad Busson`,
  `Cantons of Switzerland`,
  `Mileva Maric`,
  `Congress of Vienna`,
  `World Wide Fund for Nature`,
  `SIG SG 550`,
  `H. R. Giger`,
  `Ma Anand Sheela`,
  `Direct democracy`,
  `Maggi`,
  `Novartis`,
  `Elisabeth Kopp`,
  `UEFA Euro 2008`,
  `Belinda Bencic`,
  `Swiss Super League`,
  `Jean Piaget`,
  `Lausanne`,
  `Ineos`,
  `Clint Capela`,
  `Hans Albert Einstein`,
  `Mediterranean Shipping Company`,
  `Treaty of Lausanne`,
  `Swissair Flight 111`,
  `On (company)`,
  `Paul Dirac`,
  `International Red Cross and Red Crescent Movement`,
  `Jean-Paul Marat`,
  `Fabian Schдr`,
  `Swiss International Air Lines`,
  `Pennsylvania Dutch`,
  `Old Swiss Confederacy`,
  `Pingu`,
  `Edoardo Ponti`,
  `Rainer Maria Rilke`,
  `Heidi`,
  `Sauber Motorsport`,
  `Lucerne`,
  `FC Sion`,
  `ETH Zurich`,
  `Switzerland national football team`,
  `Meringue`,
  `Sechselдuten`,
  `Paracelsus`,
  `Gruyиre cheese`,
  `Bruno Ganz`,
  `1954 FIFA World Cup`,
  `Religious and philosophical views of Albert Einstein`,
  `Oerlikon 20 mm cannon`,
  `International Olympic Committee`,
  `2002 Ьberlingen mid-air collision`,
  `The Swatch Group`,
  `Maia arson crimew`,
  `Swiss Armed Forces`,
  `Ramona Bachmann`,
  `Invicta International Airlines Flight 435`,
  `Roche`,
  `Mattia Binotto`,
  `Institut Le Rosey`,
  `Ovaltine`,
  `Martina Hingis`,
  `Bank for International Settlements`,
  `Maximilian Schell`,
  `2022–23 Swiss Super League`,
  `List of Nestlй brands`,
  `Michele Bachmann`,
  `Daniel Bernhardt`,
  `Gianni Infantino`,
  `Zurich Airport`,
  `Christopher Chaplin`,
  `William Tell`,
  `FIBA`,
  `Romandy`,
  `Cordon bleu (dish)`,
  `Marc Forster`,
  `Lugano`,
  `Grasshopper Club Zьrich`,
  `Leontopodium nivale`,
  `1954 Geneva Conference`,
  `SIG Sauer SIG516`,
  `Logitech`,
  `Firearms regulation in Switzerland`,
  `Helmut Horten`,
  `Switzerland during the World Wars`,
  `Rhфne`,
  `Erich von Dдniken`,
  `SIG Sauer P220`,
  `STMicroelectronics`,
  `Marcel Hug`,
  `Ferdinand de Saussure`,
  `Arijanet Muric`,
  `Ingvar Kamprad`,
  `Bernhard Caesar Einstein`,
  `Gregor Kobel`,
  `List of cities in Switzerland`,
  `Robert Miles`,
  `Hans Wilsdorf`,
  `Demographics of Switzerland`,
  `Gotthard Base Tunnel`,
  `Ticino`,
  `Denis Zakaria`,
  `Celtic Frost`,
  `Gesellschaft mit beschrдnkter Haftung`,
  `Fondue`,
  `Economy of Switzerland`,
  `Flag of Switzerland`,
  `International Committee of the Red Cross`,
  `International Telecommunication Union`,
  `Geneva Bible`,
  `Canton of Geneva`,
  `Trieste (bathyscaphe)`,
  `Sergio Ermotti`,
  `Bottega Veneta`,
  `Mowag Piranha`,
  `Grisons`,
  `Federal Council (Switzerland)`,
  `Nathaniel Philip Rothschild`,
  `Nico Hischier`,
  `2022 Tour de France`,
  `Pilatus PC-9`,
  `World Intellectual Property Organization`,
  `The Palace (2023 film)`,
  `Yodeling`,
  `The Swiss Family Robinson`,
  `Chaplin family`,
  `Santiago Calatrava`,
  `Eiger`,
  `Lake Constance`,
  `Nespresso`,
  `Eugene Chaplin`,
  `Emmental cheese`,
  `Dignitas (Swiss non-profit organisation)`,
  `Gianluigi Aponte`,
  `Swiss Army knife`,
  `Marthe Keller`,
  `Swiss People's Party`,
  `Trafigura`,
  `Swiss people`,
  `Lake Geneva`,
  `Sepp Blatter`,
  `Interlaken`,
  `Servette FC`,
  `Helvetic Republic`,
  `Kevin Fiala`,
  `Huldrych Zwingli`,
  `Roman Bьrki`,
  `Hansjцrg Wyss`,
  `Audemars Piguet`,
  `Jake Canuso`,
  `Wolfgang Pauli`,
  `FC Zьrich`,
  `Alain Berset`,
  `La Tиne culture`,
  `Vitol`,
  `Lotharingia`,
  `EuroAirport Basel Mulhouse Freiburg`,
  `Thomas Winkler`,
  `Yehudi Menuhin`,
  `Irиne Jacob`,
  `Pilatus PC-7`,
  `Swiss German`,
  `Alain de Botton`,
  `Lauterbrunnen`,
  `Sociйtй а responsabilitй limitйe`,
  `Souheila Yacoub`,
  `Franco-Provenзal`,
  `Tissot`,
  `Marc Rich`,
  `2023 Tour de Romandie`,
  `Brьgger & Thomet MP9`,
  `Lake Maggiore`,
  `Vaud`,
  `Grindelwald`,
  `Stewart Ford`,
  `Alberto Giacometti`,
  `Geneva Airport`,
  `Banking in Switzerland`,
  `Pilatus PC-21`,
  `Eluveitie`,
  `Diogo Costa`,
  `Valais`,
  `2023 Swiss federal election`,
  `Pilatus PC-6 Porter`,
  `Kirsch`,
  `Habsburg Castle`,
  `Lion Monument`,
  `Mirka Federer`,
  `Syngenta`,
  `Swatch`,
  `Battle of Nдfels`,
  `Zermatt`,
  `Public holidays in Switzerland`,
  `Йcole Polytechnique Fйdйrale de Lausanne`,
  `Michelle Hunziker`,
  `Swiss neutrality`,
  `Alemannic German`,
  `Urnfield culture`,
  `Neuchвtel`,
  `Swissair`,
  `The Social Contract`,
  `Elisabeth Kьbler-Ross`,
  `Robert Louis-Dreyfus`,
  `St. Moritz`,
  `Davos`,
  `Via Francigena`,
  `Yello`,
  `National League (ice hockey)`,
  `Standard German`,
  `List of equipment of the Swiss Army`,
  `Vilfredo Pareto`,
  `Nescafй`,
  `Dean Schneider`,
  `Volkan Oezdemir`,
  `Gabriela Andersen-Schiess`,
  `St. Gallen`,
  `Daniel Bernoulli`,
  `President of the Swiss Confederation`,
  `Omega Speedmaster`,
  `Rhine Falls`,
  `Timo Meier`,
  `Zurich Insurance Group`,
  `Swiss Alps`,
  `Edelweiss Air`,
  `Swiss Federal Railways`,
  `Maria Schell`,
  `Ueli Steck`,
  `Roger Federer career statistics`,
  `Saint Maurice`,
  `Krokus (band)`,
  `Davidoff`,
  `War of the League of Cambrai`,
  `Montreux`,
  `CH`,
  `Euthanasia in Switzerland`,
  `List of works by Paul Klee`,
  `Sechs Schwedinnen im Pensionat`,
  `History of Switzerland`,
  `TE Connectivity`,
  `Canton of Bern`,
  `Taulant Xhaka`,
  `List of aircraft of the Swiss Air Force`,
  `Canton of Zьrich`,
  `Pilatus PC-24`,
  `Annus mirabilis papers`,
  `Jungfraujoch`,
  `Sabina Spielrein`,
  `Melia Kreiling`,
  `Gstaad`,
  `Youth (2015 film)`,
  `Operation Tannenbaum`,
  `Breitling SA`,
  `Kuehne + Nagel`,
  `Italian War of 1551–1559`,
  `Crossair Flight 3597`,
  `Greater Swiss Mountain Dog`,
  `Brьgger & Thomet`,
  `Locarno Treaties`,
  `Henry Wirz`,
  `Chur`,
  `Stadler FLIRT`,
  `List of banks in Switzerland`,
  `Edward Berger`,
  `Barbara Berlusconi`,
  `SIG SG 510`,
  `Viktor Korchnoi`,
  `Margarita Louis-Dreyfus`,
  `Hublot`,
  `Melissa Bonny`,
  `List of ancient Celtic peoples and tribes`,
  `Hortense de Beauharnais`,
  `Social Democratic Party of Switzerland`,
  `Nino Niederreiter`,
  `White Swiss Shepherd Dog`,
  `Francis de Sales`,
  `Hamilton Watch Company`,
  `Jaeger-LeCoultre`,
  `Panzer 68`,
  `IWC Schaffhausen`,
  `Jura Mountains`,
  `Sйbastien Buemi`,
  `Tour du Mont Blanc`,
  `Zug`,
  `Gйrald Genta`,
  `More Crap`,
  `Federal Assembly (Switzerland)`,
  `Vacheron Constantin`,
  `Tides (film)`,
  `List of Swiss cheeses`,
  `Ottmar Hitzfeld`,
  `Buddy Elias`,
  `Switzerland in the Napoleonic era`,
  `Louis Chevrolet`,
  `Politics of Switzerland`,
  `Severin Hacker`,
  `Eugиne Burnand`,
  `Oh Yeah (Yello song)`,
  `Fokker D.VII`,
  `Gebirgsjдger`,
  `Fabian Cancellara`,
  `Montreux Convention Regarding the Regime of the Straits`,
  `Neuchвtel Xamax FCS`,
  `FC Lugano`,
  `Quartz crisis`,
  `Kempinski`,
  `Luigi Lucheni`,
  `S-Bahn`,
  `National Council (Switzerland)`,
  `Henry Dunant`,
  `Thabo Sefolosha`,
  `Silvana Tirinzoni`,
  `Geneva International Motor Show`,
  `Switzerland–European Union relations`,
  `Fйdйration Internationale de Volleyball`,
  `Yomi Denzel`,
  `Clay Regazzoni`,
  `Rheinmetall Oerlikon Millennium Gun`,
  `Rolex Submariner`,
  `Niki de Saint Phalle`,
  `SIX Swiss Exchange`,
  `The Adecco Group`,
  `Helvetia`,
  `Swiss Challenge League`,
  `Germaine de Staлl`,
  `Rцsti`,
  `K31`,
  `List of alumni of Institut Le Rosey`,
  `Tchoukball`,
  `SIG Combibloc Group`,
  `Albinen`,
  `Benjamin de Rothschild`,
  `The Liberals (Switzerland)`,
  `University of Zurich`,
  `Helvetii`,
  `Jungfrau`,
  `Ernesto Bertarelli`,
  `Henry Fuseli`,
  `Bьsingen am Hochrhein`,
  `Breel Embolo`,
  `Billy Meier`,
  `Young Global Leaders`,
  `Swiss mountain dog`,
  `Julius Baer Group`,
  `Fribourg`,
  `SIG P210`,
  `Jakob Ammann`,
  `SIG Pro`,
  `Religion in Switzerland`,
  `Swissair Flight 330`,
  `FC St. Gallen`,
  `Romansh people`,
  `Rheinmetall Air Defence`,
  `Raetia`,
  `Directorial system`,
  `Schaffhausen`,
  `Ultra-Trail du Mont-Blanc`,
  `Йdouard Stern`,
  `7.5Ч55mm Swiss`,
  `Gunter Sachs`,
  `John Sutter`,
  `Air Defense Anti-Tank System`,
  `Philippe Senderos`,
  `Stephanie Egger`,
  `Fidelis of Sigmaringen`,
  `Patrick Moraz`,
  `Stadler Rail`,
  `Schindler Group`,
  `Jacques Necker`,
  `Gotthard Road Tunnel`,
  `Migros`,
  `Tatort`,
  `1977 Nestlй boycott`,
  `Andy Hug`,
  `Sandra Hess`,
  `FC Luzern`,
  `Ron Kass`,
  `Tariq Ramadan`,
  `Ad Infinitum (metal band)`,
  `Stephan Lichtsteiner`,
  `Coins of the Swiss franc`,
  `Financial Stability Board`,
  `Jacob Bernoulli`,
  `Tour de Romandie`,
  `Swiss mercenaries`,
  `Jacques Piccard`,
  `Michael Platt (financier)`,
  `Mont Blanc massif`,
  `EasyJet Switzerland`,
  `Federer–Nadal rivalry`,
  `National Redoubt (Switzerland)`,
  `Hellhammer`,
  `Emile, or On Education`,
  `Canton of Neuchвtel`,
  `Swiss chocolate`,
  `Gotthard Tunnel`,
  `My Life as a Courgette`,
  `Albert Gallatin`,
  `Breguet (brand)`,
  `Paloma Elsesser`,
  `List of Swiss companies by revenue`,
  `Alamannia`,
  `Aerial incidents in Switzerland in World War II`,
  `Lucien Favre`,
  `Italian orthography`,
  `Cйsar Ritz`,
  `Zenith (watchmaker)`,
  `Frank Schaeffer`,
  `Valais Blacknose`,
  `Oriflame`,
  `Alphorn`,
  `SGS S.A.`,
  `Geneva Protocol`,
  `List of career achievements by Roger Federer`,
  `Mцvenpick Hotels & Resorts`,
  `Chillon Castle`,
  `Vehicle registration plates of Switzerland`,
  `Western Romance languages`,
  `Vevey`,
  `Ricardo Rodriguez (footballer)`,
  `FC Lausanne-Sport`,
  `Remo Forrer`,
  `Reichenbach Falls`,
  `Chalet`,
  `List of things named after Leonhard Euler`,
  `Remo Freuler`,
  `Aargau`,
  `Hans Urs von Balthasar`,
  `Political views of Albert Einstein`,
  `Crans-Montana`,
  `Auguste Piccard`,
  `Swiss Re`,
  `Holcim`,
  `David Bennent`,
  `Victorinox`,
  `Swatch Internet Time`,
  `United Nations Office at Geneva`,
  `Telephone numbers in Switzerland`,
  `Louis Agassiz`,
  `2019 Swiss federal election`,
  `Glacier Express`,
  `VistaJet`,
  `Djokovic–Federer rivalry`,
  `Coop (Switzerland)`,
  `Locarno Festival`,
  `Biel/Bienne`,
  `Antoni Patek`,
  `Transocean`,
  `Monte Rosa`,
  `Italian War of 1494–1495`,
  `Winterthur`,
  `Meyer Guggenheim`,
  `Switzerland women's national football team`,
  `Pilatus Aircraft`,
  `Kapellbrьcke`,
  `Swiss National Bank`,
  `Rhaeto-Romance languages`,
  `.ch`,
  `Stade de Genиve`,
  `Gцkhan Inler`,
  `Montreux Jazz Festival`,
  `Johann Bernoulli`,
  `Barry Callebaut`,
  `Sonderbund War`,
  `International Typographic Style`,
  `Rupperswil murder case`,
  `Sven Michel`,
  `DJ BoBo`,
  `Swiss cuisine`,
  `Jonas Siegenthaler`,
  `Lia Wдlti`,
  `Zeki Amdouni`,
  `SIG SG 540`,
  `Burning Witches`,
  `Marcel Koller`,
  `Sulzer (manufacturer)`,
  `Givaudan`,
  `Group of Ten (IMF)`,
  `Locarno`,
  `Restoration and Regeneration in Switzerland`,
  `Alexander Frei`,
  `University of Basel`,
  `Genиve-Servette HC`,
  `Ignazio Cassis`,
  `Thomas Gabriel Fischer`,
  `La Chaux-de-Fonds`,
  `Oliver Carter (wrestler)`,
  `Hermann Weyl`,
  `Swiss nationality law`,
  `Edmond de Rothschild Group`,
  `Urs Fischer (footballer)`,
  `Gallo-Italic languages`,
  `Protestant Church of Switzerland`,
  `GAVI`,
  `Pilatus (mountain)`,
  `Fourth Geneva Convention`,
  `Lucerne hammer`,
  `Discourse on Inequality`,
  `Burgundian Wars`,
  `Robert Frank`,
  `International Federation of Red Cross and Red Crescent Societies`,
  `Patek Philippe Henry Graves Supercomplication`,
  `Holcim Group`,
  `Steven Zuber`,
  `The Centre (political party)`,
  `Kevin Mbabu`,
  `Alitalia Flight 404`,
  `Djibril Sow`,
  `Eldin Jakupovic`,
  `Appenzeller Sennenhund`,
  `List of Swiss people by net worth`,
  `Swiss Guards`,
  `Helvetic Airways`,
  `Partners Group`,
  `Angelica Kauffman`,
  `Lake Lucerne`,
  `Andi Zeqiri`,
  `Swiss mini gun`,
  `University of Geneva`,
  `Benny's Video`,
  `Bally (fashion house)`,
  `Intersport`,
  `Rivella`,
  `Angelus Novus`,
  `Eurovision Song Contest 1956`,
  `ETA SA`,
  `Ladyva`,
  `Conscription in Switzerland`,
  `Herzog & de Meuron`,
  `Geography of Switzerland`,
  `Chopard`,
  `To Mega Therion (album)`,
  `FC Winterthur`,
  `Canton of Schwyz`,
  `Liechtenstein–Switzerland relations`,
  `Movado`,
  `Graduate Institute of International and Development Studies`,
  `Bernoulli family`,
  `Basel-Stadt`,
  `Growth of the Old Swiss Confederacy`,
  `House of Zдhringen`,
  `Joan Gamper`,
  `Friedrich Dьrrenmatt`,
  `Palace of Nations`,
  `The Collected Works of C. G. Jung`,
  `Ylena In-Albon`,
  `University of St. Gallen`,
  `Canton of Jura`,
  `Heidi (2015 film)`,
  `Great St Bernard Pass`,
  `Jet d'Eau`,
  `Informa`,
  `Nyon`,
  `Appenzell Innerrhoden`,
  `Theodore Schurch`,
  `Canton of Uri`,
  `Mike Horn`,
  `Swiss Standard German`,
  `Johanna Spyri`,
  `Emma Jung`,
  `Ruddy shelduck`,
  `Czapek & Cie`,
  `Hans Heinrich Thyssen-Bornemisza`,
  `Eugen Bleuler`,
  `Lake Zurich`,
  `Swiss French`,
  `Niklaus Wirth`,
  `St. Jakob-Park`,
  `Canton of St. Gallen`,
  `The Visit (play)`,
  `Dieter Meier`,
  `Stadler KISS`,
  `Bellinzona`,
  `Bell & Ross`,
  `Swissport`,
  `Frдulein`,
  `Visa requirements for Swiss citizens`,
  `Italo-Western languages`,
  `Swiss Confederation (Napoleonic)`,
  `Council of States (Switzerland)`,
  `Bernina Express`,
  `List of political parties in Switzerland`,
  `Night Train to Lisbon (film)`,
  `F. P. Journe`,
  `Sovereigntism`,
  `Mettler Toledo`,
  `Northwood University`,
  `Solvay Hut`,
  `Galderma`,
  `Swiss passport`,
  `Frithjof Schuon`,
  `Roman Josi`,
  `Northmen: A Viking Saga`,
  `Arthur Chevrolet`,
  `Anton Mosimann`,
  `Solar Impulse`,
  `Lausanne Mйtro`,
  `Battle of Marignano`,
  `Solothurn S-18/1000`,
  `Education in Switzerland`,
  `Miriam Cahn`,
  `Lonza Group`,
  `Gotthard Pass`,
  `Italian War of 1521–1526`,
  `Johann Heinrich Pestalozzi`,
  `Frйdйrique Constant`,
  `Letzigrund`,
  `Rolex Datejust`,
  `Ramon Vega`,
  `List of wars involving Switzerland`,
  `Rolex GMT Master II`,
  `Firmenich`,
  `Charles Dutoit`,
  `Swiss Federal Constitution`,
  `Oris`,
  `Sergei Mikhailov (businessman)`,
  `Stadion Wankdorf`,
  `LGBT rights in Switzerland`,
  `List of universities in Switzerland`,
  `German-speaking Switzerland`,
  `Art Basel`,
  `Saanen goat`,
  `Baume et Mercier`,
  `Xstrata`,
  `Shooting an apple off one's child's head`,
  `Stefan Frei`,
  `International Institute for Management Development`,
  `Zьrich Hauptbahnhof`,
  `2021–22 Swiss Super League`,
  `Cedric Itten`,
  `Canton of Fribourg`,
  `Joseph Odermatt`,
  `Edmond Adolphe de Rothschild`,
  `Women's suffrage in Switzerland`,
  `Chancellor of Switzerland`,
  `Crypto AG`,
  `Swiss made`,
  `Fйdйration Aйronautique Internationale`,
  `Bernese Oberland`,
  `Upper German`,
  `Cervelat`,
  `List of presidents of the Swiss Confederation`,
  `Peter Zumthor`,
  `MG 51`,
  `Immigration to Switzerland`,
  `STOXX Europe 600`,
  `Swiss Italian`,
  `ZSC Lions`,
  `Islam in Switzerland`,
  `Pictet Group`,
  `Pajtim Kasami`,
  `Pacojet`,
  `Switzerland–NATO relations`,
  `Oliver Tobias`,
  `EHC Biel`,
  `Paul-Andrй Cadieux`,
  `Eurovision Song Contest 1989`,
  `Maus Frиres`,
  `Abbey of Saint Gall`,
  `Name of Switzerland`,
  `Pharmaceutical industry in Switzerland`,
  `SIG Sauer SSG 3000`,
  `Cannabis in Switzerland`,
  `Federer family`,
  `Thun`,
  `Union Bank of Switzerland`,
  `Mathey-Tissot`,
  `Francesco Borromini`,
  `Franck Muller`,
  `Christian Democratic People's Party of Switzerland`,
  `Piaget SA`,
  `Li Tobler`,
  `Guy Parmelin`,
  `Healthcare in Switzerland`,
  `Johan Djourou`,
  `Yeslam bin Ladin`,
  `Collиge du Lйman`,
  `Flags and arms of cantons of Switzerland`,
  `Morbid Tales`,
  `Susanne Bartsch`,
  `Corsier-sur-Vevey`,
  `Jacob Burckhardt`,
  `Benjamin Siegrist`,
  `Xenia Tchoumitcheva`,
  `Rolex Milgauss`,
  `Girard-Perregaux`,
  `2021 European floods`,
  `ALR Piranha`,
  `Italy (geographical region)`,
  `Ricola`,
  `Marc-Andrea Hьsler`,
  `Canton of Glarus`,
  `FC Wil`,
  `Free Democratic Party of Switzerland`,
  `Tolochenaz`,
  `Ana-Maria Crnogorcevic`,
  `Treaty of Paris (1814)`,
  `COSC`,
  `Scott Sports`,
  `Julius Maggi`,
  `Landjдger`,
  `Daniele Ganser`,
  `Titlis`,
  `Green Party of Switzerland`,
  `Esther Dyson`,
  `Basel Accords`,
  `Universal Genиve`,
  `Suisse Secrets`,
  `Canton of Lucerne`,
  `Evelyne Daitz`,
  `Wella`,
  `Adrien Philippe`,
  `Sika AG`,
  `1961 European Cup final`,
  `Lorik Cana`,
  `Solothurn`,
  `SIG Sauer P238`,
  `RUAG`,
  `Third Geneva Convention`,
  `List of Swiss International Air Lines destinations`,
  `Bruno Manser`,
  `Dahu`,
  `Marie-Louise von Franz`,
  `James Thiйrrйe`,
  `Rhaetian people`,
  `Cowbell`,
  `Dufourspitze`,
  `Johann Ludwig Burckhardt`,
  `Blue Brain Project`,
  `Ne partez pas sans moi`,
  `Princess Nina of Greece and Denmark`,
  `Swiss association`,
  `Swiss Promotion League`,
  `Walter Thurnherr`,
  `Albian Ajeti`,
  `List of international organizations based in Geneva`,
  `Wenger`,
  `Canton of Zug`,
  `List of scientific publications by Albert Einstein`,
  `Fritz Zwicky`,
  `Sphinx Observatory`,
  `Joлl Dicker`,
  `Sophie Taeuber-Arp`,
  `Karin Keller-Sutter`,
  `2026 IIHF World Championship`,
  `Felix Bloch`,
  `Behgjet Pacolli`,
  `Escher Wyss & Cie.`,
  `Kunstmuseum Basel`,
  `Michael Casanova`,
  `Urs Bьhler`,
  `Goetheanum`,
  `Bob Lutz (businessman)`,
  `Alpine Mastiff`,
  `Culture of Switzerland`,
  `Teddy Stauffer`,
  `Julien Blanc`,
  `Jakow Trachtenberg`,
  `Military ranks of Switzerland`,
  `Swiss Arms`,
  `Coroner (band)`,
  `Thurgau`,
  `Maren Haile-Selassie`,
  `Lago Bianco`,
  `Hans Kьng`,
  `Unus pro omnibus, omnes pro uno`,
  `Bertrand Piccard`,
  `SIG Sauer P239`,
  `Cereal Partners Worldwide`,
  `Switzerland in the Eurovision Song Contest`,
  `Harry Gold`,
  `Beny Steinmetz`,
  `Haute Route`,
  `Rhaetian Railway`,
  `Simplon Tunnel`,
  `Meiringen Air Base`,
  `Ernest Bloch`,
  `Early Germanic culture`,
  `Aare`,
  `Swiss football league system`,
  `Prostitution in Switzerland`,
  `Beatrice Egli`,
  `FC Thun`,
  `Lepontic language`,
  `Into the Pandemonium`,
  `Cabaret Voltaire (Zurich)`,
  `Baden, Switzerland`,
  `Katharina Bцhm`,
  `2020 IIHF World Championship`,
  `Swiss Plateau`,
  `Andrea Orcel`,
  `Latin Union`,
  `Landwehr`,
  `Toni Wolff`,
  `Mцvenpick Ice Cream`,
  `Weatherford International`,
  `Swiss Cup`,
  `Grossmьnster`,
  `Benjamin Constant`,
  `Stan Wawrinka career statistics`,
  `Schwyz`,
  `Wilhelm Gustloff`,
  `Disappearance of Alessia and Livia Schepp`,
  `Yverdon-Sport FC`,
  `Ulysse Nardin`,
  `Jonas Omlin`,
  `Max Frisch`,
  `Gotthard (band)`,
  `Mido (watch)`,
  `Ueli Maurer`,
  `Nicolas Hayek`,
  `Festina`,
  `Basel-Landschaft`,
  `Brown, Boveri & Cie`,
  `Vincent Perez`,
  `List of companies of Switzerland`,
  `EFG International`,
  `Mowag Duro`,
  `Swiss Party of Labour`,
  `Pingu in the City`,
  `Valon Behrami`,
  `Lardo`,
  `Arthur Honegger`,
  `Wengen`,
  `French invasion of Switzerland`,
  `Lake Lugano`,
  `Julie; or, The New Heloise`,
  `Philipp Hildebrand`,
  `Gruyиres`,
  `Broken Chair`,
  `George de Mestral`,
  `Taiwan frigate scandal`,
  `Aarau`,
  `Verbier`,
  `Henri Guisan`,
  `Adrian Frutiger`,
  `Three Leagues`,
  `Foreign relations of Switzerland`,
  `Mьrren`,
  `Argand lamp`,
  `Max Bill`,
  `Tilsit cheese`,
  `Oliver Neuville`,
  `Inn (river)`,
  `Confessions (Rousseau)`,
  `Swisscom`,
  `Aare Gorge`,
  `Green Liberal Party of Switzerland`,
  `Ulrich Kцrner`,
  `Patrick Chappatte`,
  `Battle of Sempach`,
  `Goodbye to Language`,
  `Swiss-type cheeses`,
  `History of the Jews in Switzerland`,
  `Crime in Switzerland`,
  `Gjon's Tears`,
  `2022–23 NL season`,
  `University of Fribourg`,
  `List of mass shootings in Switzerland`,
  `OC Oerlikon`,
  `Robert Walser (writer)`,
  `Heidi (2015 TV series)`,
  `Certina`,
  `Morges`,
  `Lдderach`,
  `Early Modern Switzerland`,
  `Mercuria`,
  `Claus Wedekind`,
  `Alan Howard (hedge fund manager)`,
  `Brown Swiss cattle`,
  `SIG MG 710-3`,
  `Swiss Football Association`,
  `Stйphane Chapuisat`,
  `Walter Rudolf Hess`,
  `John Reece`,
  `Mйret Oppenheim`,
  `Franзois Genoud`,
  `Bank Lombard Odier & Co`,
  `Lйon Walras`,
  `Kindlifresserbrunnen`,
  `Contributions of Leonhard Euler to mathematics`,
  `University of Lausanne`,
  `Mowag`,
  `Vaz/Obervaz`,
  `Darko Jevtic`,
  `Swiss 1. Liga (football)`,
  `Tourism in Switzerland`,
  `Gentian liqueur`,
  `Bern Airport`,
  `Voting in Switzerland`,
  `SIG Sauer P938`,
  `DKSH`,
  `Sisi & I`,
  `Alfred Escher`,
  `Stйphane Henchoz`,
  `Simona de Silvestro`,
  `Saidy Janko`,
  `Peter Sauber`,
  `Swabian War`,
  `Cold Lake (album)`,
  `Villa Diodati`,
  `Torstein Hagen`,
  `Rhodanic Republic`,
  `Swiss Americans`,
  `Crossair`,
  `Brig-Glis`,
  `Reformation in Switzerland`,
  `Mammut Sports Group`,
  `Murat Yakin`,
  `Swiss Psalm`,
  `FC Chiasso`,
  `Johannes Itten`,
  `Cologny`,
  `Gaetano Berardi`,
  `Aiglon College`,
  `Duino Elegies`,
  `Monotheist (album)`,
  `Christian Gross`,
];

const arr2 = [];

function getTwenty(document) {
  if (!document) {
    return '';
  }
  let count = 0;
  let result = '';
  while (count < 20) {
    result += document.sentences()[count]?.text() + ' ';
    count++;
  }
  return result + '\n' + '\n';
}

arr.forEach(async (elem) => {
  if (!elem) {
    return;
  }

  if (elem.includes('article')) {
    return;
  }
  let doc = await wtf.fetch(elem);

  fs.appendFile('./test.txt', getTwenty(doc), function (err) {
    if (err) {
      return console.log(err);
    }
    console.log('The file was saved!');
  });
});
